version: "3.8"

services:
  docker-events:
    image: rjchicago/docker-events:${VERSION:-latest}
    environment:
      DOCKER_EVENTS_SINCE: ${DOCKER_EVENTS_SINCE:-0s}
      HOSTNAME: "{{.Node.Hostname}}"
      SWARM_NAME: "${SWARM_NAME:-SWARM_NAME}"
      METRIC_EVENT_TYPES: "container" # comma separated
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      labels:
        - traefik.enable=true
        - traefik.docker.network=${TRAEFIK_NET:-traefik-net-admin}
        - traefik.http.routers.docker-events.rule=${TRAEFIK_RULE}
        - traefik.http.services.docker-events.loadbalancer.server.port=3000
